# Generated by Django 5.0.7 on 2024-07-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_move_body_to_body_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='radix_id',
            field=models.IntegerField(default=0),
        ),
    ]
